name: todolistapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  awesome_notifications: ^0.10.1
  supabase_flutter: ^2.10.0
  permission_handler: ^12.0.1
  google_sign_in: ^6.2.1
  flutter_feather_icons: ^2.0.0+1
  percent_indicator: ^4.2.5
  confetti: ^0.8.0
  fl_chart: ^0.65.0
  table_calendar: ^3.2.0
  vector_math: ^2.1.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
  remove_alpha_ios: true
